<?php

namespace Tests;

use Faker\Factory;
use Faker\Generator;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use Illuminate\Support\Facades\Artisan;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    private Generator $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('migrate:refresh');
        Artisan::call('db:seed');
        $this->faker = Factory::create();
    }

    public function __get($key)
    {

        if ($key === 'faker')
            return $this->faker;
        throw new \Exception('Unknown Key Requested');
    }
}
